server:
  port: 9090
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: "uaapdatawebapp"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
  datasource:
    url: "jdbc:mysql://localhost:3306/test"
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

#EUREKA-SERVICE REGISTRY
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "uaapdatawebapp"
    description: "UAAP Data web app"
    version: "1.0.0"
