server:
  port: 9090
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: "uaapdatawebapp"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true


info:
  app:
    name: "uaapdatawebapp"
    description: "UAAP Data web app"
    version: "1.0.0"
