apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.deploymentName }}
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      containers:
        - name: {{ .Values.appLabel }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.global.datasourcePassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.datasource.db }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi