apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appLabel }}
spec:
  ports:
    - port: {{ .Values.containerPort }}
  clusterIP: None  # Headless service to allow stable DNS names for StatefulSet
  selector:
    app: {{ .Values.appLabel }}