{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.appLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      containers:
        - name: {{ .Values.appLabel }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
          {{- if .Values.profile_enabled }}
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_PROFILES_ACTIVE
          {{- end }}

          {{- if .Values.config_enabled }}
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_CONFIG_IMPORT
          {{- end }}

          {{- if .Values.discoveryServer_enabled }}
          - name: SPRING.CLOUD.KUBERNETES.DISCOVERY.DISCOVERY-SERVER-URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING.CLOUD.KUBERNETES.DISCOVERY.DISCOVERY-SERVER-URL
          {{- end }}

          {{- if .Values.datasourceUrl_enabled }}
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_DATASOURCE_URL
          {{- end }}

          {{- if .Values.datasourceUser_enabled }}
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_DATASOURCE_USERNAME
          {{- end }}

          {{- if .Values.datasourcePassword_enabled }}
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_DATASOURCE_PASSWORD
          {{- end }}

          {{- if .Values.configServerGit_enabled }}
          - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
          {{- end }}

  {{- end -}}