server:
  port: 8080

spring:
  application:
    name: "uaapstatsdata"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
  datasource:
    url: "jdbc:mysql://localhost:3306/test"
    username: springstudent
    password: springstudent
#    initialize: false
#    schema: none
#    data: none
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

#EUREKA-SERVICE REGISTRY
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "uaapstatsdata"
    description: "UAAP Data Scraper data"
    version: "1.0.0"