### H2 Test Database creds
#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#    initialization-mode: always
#    initialize: false
#    schema: none
#    data: none
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create-drop
#  show-sql: true
#  h2:
#    console:
#      enabled: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    shutdown:
#      enabled: true
#  info:
#    env:
#      enabled: true
#
#endpoints:
#  shutdown:
#    enabled: true
#
#
#info:
#  app:
#    name: "uaapstatsdata"
#    description: "UAAP Data Scraper data"
#    version: "1.0.0"
#
#server:
#  port: 8080