apiVersion: v1
kind: ConfigMap
metadata:
  name: uaapdata-configmap
data:
  SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
  SPRING_PROFILES_ACTIVE: "default"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka"
  SPRING.CLOUD.KUBERNETES.DISCOVERY.DISCOVERY-SERVER-URL: "http://spring-cloud-kubernetes-discoveryserver:80/"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-0.mysql:3306/uaapdatadb"
  SPRING_DATASOURCE_USERNAME: "root"
  MYSQL_ROOT_PASSWORD: "my-secret-password"
  SPRING_SQL_INIT_MODE: "never"
  MYSQL_DATABASE: "uaapdatadb"
