apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  labels:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: runardo/configserver:v2
          ports:
          - containerPort: 8071
          env:
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              valueFrom:
                configMapKeyRef:
                  name: uaapdata-configmap
                  key: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
---
apiVersion: v1
kind: Service
metadata:
  name: configserver
spec:
  selector:
    app: configserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071