apiVersion: apps/v1
kind: Deployment
metadata:
  name: uaapstatsdata-deployment
  labels:
    app: uaapstatsdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uaapstatsdata
  template:
    metadata:
      labels:
        app: uaapstatsdata
    spec:
      containers:
        - name: uaapstatsdata
          image: runardo/uaapstatsdata:v2
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: uaapdata-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: uaapdata-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING.CLOUD.KUBERNETES.DISCOVERY.DISCOVERY-SERVER-URL
              valueFrom:
                configMapKeyRef:
                  name: uaapdata-configmap
                  key: SPRING.CLOUD.KUBERNETES.DISCOVERY.DISCOVERY-SERVER-URL
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: uaapdata-configmap
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: uaapdata-configmap
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: uaapdata-configmap
                  key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: uaapstatsdata
spec:
  selector:
    app: uaapstatsdata
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080