apiVersion: apps/v1
kind: Deployment
metadata:
  name: uaapstatscraper-deployment
  labels:
    app: uaapstatscraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uaapstatscraper
  template:
    metadata:
      labels:
        app: uaapstatscraper
    spec:
      containers:
        - name: uaapstatscraper
          image: runardo/uaapstatscraper:v2
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: uaapdata-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: uaapdata-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING.CLOUD.KUBERNETES.DISCOVERY.DISCOVERY-SERVER-URL
              valueFrom:
                configMapKeyRef:
                  name: uaapdata-configmap
                  key: SPRING.CLOUD.KUBERNETES.DISCOVERY.DISCOVERY-SERVER-URL
---
apiVersion: v1
kind: Service
metadata:
  name: uaapstatscraper
spec:
  selector:
    app: uaapstatscraper
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081