apiVersion: apps/v1
kind: Deployment
metadata:
  name: statscraper-deployment
  labels:
    app: statscraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statscraper
  template:
    metadata:
      labels:
        app: statscraper
    spec:
      containers:
        - name: statscraper
          image: runardo/uaapstatscraper:v1
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: uaapdata-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: uaapdata-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: uaapdata-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: statscraper
spec:
  selector:
    app: statscraper
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081